### ISSUE TITLE
[feature-request] copyWithout

### ISSUE THREAD

**Issue by lslv1243** [bnxm/dart-data-class-generator#16]
Nice extension! 

I opened an issue to add this feature on the dart language but I think it will take a while to be implemented. I found your extension and liked it immediately. I would like to request a feature to set null to a value when using copyWith.

There is this approach that I recommended in the issue: 
https://github.com/dart-lang/language/issues/961#issue-617422862

And there is this guy approach that I liked a lot too:
https://github.com/dart-lang/language/issues/961#issuecomment-636522739

I would be very happy if you implemented any of these.

Thanks for your extension!

**Comment by Abion47** [comment]
The `copyWithout` method can be potentially useful, but I greatly disapprove of the second option linked. Abstracting the data type of the parameter into an `Object` as well as relying on a magic global `Unused` object for the "without" parameters? It reeks of an anti-pattern.

**Comment by bnxm** [comment]
I think I wont have the time to implement this, as the use case seems fairly limited and especially in lights of the upcoming support for non-nullable data types, this will be harder to implement without using hacky workarounds.
