### ISSUE TITLE
[feature-request] create code without lint errors

### ISSUE THREAD

**Issue by sgehrman** [bnxm/dart-data-class-generator#17]
This tool is great, but I have to then fix all the lint errors by hand.

Install 'lint' and use this for analysis-options  https://github.com/passsy/dart-lint/blob/master/lib/analysis_options.yaml

You'll see a ton of errors from you generated code.

**Comment by bnxm** [comment]
You'll have to use these linting rules, at least when you need json serialization:

~~~yaml
implicit-casts: false
implicit-dynamic: false
~~~

I'll close this in favor of #22.
