### ISSUE TITLE
[feature-request] Generate assert for class parameters.

### ISSUE THREAD

**Issue by Prn-Ice** [bnxm/dart-data-class-generator#18]
I can generate asserts for methods, I'm not sure if this comes from your extension but I noticed it after I installed your extension and it would be nice if I had that feature for classes.
![Peek 2020-06-15 13-57](https://user-images.githubusercontent.com/48252841/84659989-239c3a00-af10-11ea-80eb-323ea207b2d1.gif)

**Comment by bnxm** [comment]
Considering that flutter will soon support non-nullable types, I think this will no longer be needed so I'll close this one
