### ISSUE TITLE
Doesn't work with enum fields

### ISSUE THREAD

**Issue by Abion47** [bnxm/dart-data-class-generator#19]
When I define a class where some of the fields are of an enum type (e.g. `enum EnumType { a, b, c }`), the extension still treats them as classes and generates code that calls `EnumType.fromMap` and `enumField.toMap`, even though neither of these methods exists (or even can exist) on an enum type. (It's technically possible to add a `toMap` method to an enum type via extension methods, but this isn't possible for `fromMap` since static extension methods are not currently supported and that is the greater use case anyway).

There are two ways to conceivably parse an enum - as integers or as strings. In the former case, the "fromMap" would have to become `enumType.values[map["key"]]` and the "toMap" would have to become `enumType.values.indexOf(enumField)`. In the latter case, the plugin would have to automatically generate utility methods `enumTypeToString` and `stringToEnumType` with switch cases to handle the parsing:

```dart
EnumType stringToEnumType(String str) {
  switch (str) {
    case 'a':
      return EnumType.a;
    case 'b':
      return EnumType.b;
    case 'c':
      return EnumType.c;
    default:
      return null;
  }
}

String enumTypeToString(EnumType e) {
  switch (e) {
    case EnumType.a:
      return 'a';
    case EnumType.b:
      return 'b';
    case EnumType.c:
      return 'c';
    default:
      return null;
  }
}
```

Alternatively, using constant maps rather than utility methods:

```dart
const Map<String, EnumType> stringToEnumType = const {
  'a': EnumType.a,
  'b': EnumType.b,
  'c': EnumType.c,
};

const Map<EnumType, String> enumTypeToString = const {
  EnumType.a: 'a',
  EnumType.b: 'b',
  EnumType.c: 'c',
};
```

It's unclear whether the plugin can automatically deduce which approach to go with. The options I see are implementing both and rely on type-checking to know which approach to use at runtime, prompt the user which approach to take for each individual field detected with an enum type, or utilize a custom annotation system (which would require a supplemental dev package).

**Comment by bnxm** [comment]
Yes, indeed `enums` are not supported because the extension relies fully on regular expressions and manual string parsing so it is impossible for the generator to know whether a type is an `enum` or a regular `class`. 

The generator also cannot not know the fields of the `enum` which is why only the approach using the index would work. 

I think creating a separate `dev-package` would be not the best solution as this is not a pub package and dependent on the IDE. Maybe a better solution would be to use comments like the dart extension does to ignore lint rules. 

```dart
// @enum
final EnumType myEnum;
```

**Comment by Abion47** [comment]
The index approach wouldn't work for situations where the enum exists in the incoming map/JSON as a string value. To be truly useful, there needs to be a way to tell the parser whether the incoming type will be an `int` or ` String`. Without using the dart linter to inspect the enum type itself, the only solution I can think of would be to have the comment flag support an optional list of string values:

(User Code)
```dart
class MyClass {
  // @enum {a, b, c}
  final EnumType myEnum;
}
```

(Generated Code)
```dart
...
static const __StringToMyEnum = {
  'a': MyEnum.a,
  'b': MyEnum.b,
  'c': MyEnum.c,
};

static const __MyEnumToString = {
  MyEnum.a: 'a',
  MyEnum.b: 'b',
  MyEnum.c: 'c',
};

Map<String, dynamic> toMap() {
  return {
    'myEnum': __MyEnumToString[myEnum],
  };
}

static Data fromMap(Map<String, dynamic> map) {
  if (map == null) return null;

  return Data(
    myEnum: __StringToMyEnum[map['myEnum']],
  );
}
```

The annoying aspect of this approach is, of course, the lack of static type safety, so if the user ever changes the values in `MyEnum`, the data class will have to be regenerated.

(On a somewhat tangential note, is there a reason the `fromMap` method is a static method and not a factory method?)

**Comment by bnxm** [comment]
> The index approach wouldn't work for situations where the enum exists in the incoming map/JSON as a string value.

I'm not sure what you mean by this... When would the enum ever exist as a `String` value, when it was previously stored as an `int`?

> ~~~dart
> static const __StringToMyEnum = {
>   'a': MyEnum.a,
>   'b': MyEnum.b,
>   'c': MyEnum.c,
> };
> 
> static const __MyEnumToString = {
>   MyEnum.a: 'a',
>   MyEnum.b: 'b',
>   MyEnum.c: 'c',
> };
> ~~~

The same could maybe be written in a one liner and without the need to specify the fields like this:

~~~dart
Map<String, dynamic> toMap() {
  return {
    'myEnum':  myEnum?.toString(),
  };
}

static Data fromMap(Map<String, dynamic> map) {
  if (map == null) return null;

  return Data(
    myEnum: Enum.values.firstWhere((e) => '$e' == map['myEnum'], orElse: () => Enum.values[0]),
  );
}
~~~

> On a somewhat tangential note, is there a reason the fromMap method is a static method and not a factory method?

That is actually a good question. I'll change that in the next version.

**Comment by Abion47** [comment]
> I'm not sure what you mean by this... When would the enum ever exist as a String value, when it was previously stored as an int?

Enums coming from (or being sent to) an API don't necessarily exist as integers. In fact, it is quite common that they can be a string value with a specific set of possible values that would most naturally deserialize as an enum instead of a plain string value. For example:

(Incoming data from "api.some-animal-data.com")
```json
{
  "animals": [{
    "id": 1,
    "type": "mammal",
    "name": "tiger"
  }, {
    "id": 2,
    "type": "bird",
    "name": "swan"
  }, {
    "id": 3,
    "type": "reptile",
    "name": "lizard"
  }, {
    "id": 4,
    "type": "amphibian",
    "name": "frog"
  }, {
    "id": 5,
    "type": "fish",
    "name": "trout"
  }]
}
```

In the API response above, the value of `type` can be one of five values: mammal, bird, reptile, amphibian, or fish. Since this is the very definition of an enumerated type, rather than storing and manipulating it as a plain string, it would make the most sense to model it as an enum value in Dart:

```dart
enum AnimalType { mammal, bird, reptile, amphibian, fish }

class Animal {
  final int id;
  final AnimalType type;
  final String name;
}
```
As such, I would expect to be able to configure the plugin to allow me to specify that.

It is possible to eliminate the map and use a `toString` approach instead, though your method takes a bit of tweaking to make it result in string values of "a", "b", or "c" rather than "MyEnum.a", "MyEnum.b", or "MyEnum.c":

```dart
Map<String, dynamic> toMap() {
  return {
    'myEnum':  myEnum?.toString()?.substring('$myEnum'.indexOf('.') + 1),
  };
}

static Data fromMap(Map<String, dynamic> map) {
  if (map == null) return null;

  return Data(
    myEnum: Enum.values.map((e) => e.toString().substring('$e'.indexOf('.') + 1))
                       .firstWhere((e) => '$e' == map['myEnum'], orElse: () => null),
  );
}
```

My personal qualm with this approach is it will not have constant-time speed, and instead have to be dynamically parsed and evaluated. Of course, unless the enum type in question had thousands or tens of thousands of values, the performance difference would be negligible, but it would still probably rub some people the wrong way as being a blatantly sub-optimal approach.

However, this wouldn't address the ambiguity of whether the user wants the enums to be parsed as `int` or as `String`, so at the very least the comment still needs to address that:

```dart
// enum
MyEnum defaultParsingBehavior; // Defaults to int parsing, maybe configurable in a setting

// enum {int} 
MyEnum explicitlyParsedAsInt; 

// enum {string}
MyEnum explicitlyParsedAsString;
```

**Comment by grand-china** [comment]
@Abion47   i think u are right;   my problem  is   enum  is not just  increase progressively;     
Moreover, enumeration values are strings, which is too common;


use ``` MyEnum?.values[map['dataType']] ```  is  need more think


enum MyEnum {

@JsonValue(1)
water,

@JsonValue(3)
apple,

@JsonValue(5)
cat,
}
