### ISSUE TITLE
Error in generating data class when there is a comment between the class and imports

### ISSUE THREAD

**Issue by osaxma** [bnxm/dart-data-class-generator#23]
The three screenshots below shows the issue. It only happens when:
- there is already an import on top
- there is a comment ( // or /// ) between the import and the to be generated class

![1](https://user-images.githubusercontent.com/46427323/92738220-6db48080-f384-11ea-974e-1b8b4b19e705.png)
![2](https://user-images.githubusercontent.com/46427323/92738240-71480780-f384-11ea-99bf-12fce19195fa.png)

<img width="929" alt="3" src="https://user-images.githubusercontent.com/46427323/92737540-e9fa9400-f383-11ea-838d-08ded0efc6b8.png">

flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.21.0-10.0.pre.161, on Mac OS X 10.15.6 19G2021, locale en)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.48.2)
[✓] Connected device (3 available)

• No issues found!

```

Dart Data Generator class version: 0.4.2

**Comment by bnxm** [comment]
Version `0.4.3` should fix this issue. If not, feel free to reopen.

**Comment by osaxma** [comment]
Thank you @bnxm -- I appreciate your work 🙏🏽
