### ISSUE TITLE
Can't find on marketplace

### ISSUE THREAD

**Issue by rathod-sahaab** [bnxm/dart-data-class-generator#29]
VScode
```
code -v
1.49.1
58bb7b2331731bf72587010e943852e13e6fd3cf
x64
```
OS
manjaro

![Screenshot from 2020-10-25 14-49-59](https://user-images.githubusercontent.com/31929374/97103281-7ad9c480-16d1-11eb-9f06-69184c18a4e6.png)

**Comment by rathod-sahaab** [comment]
Yes I downloaded the .vsix package from there, I uninstalled that and still cant find the package on marketplace
![Screenshot from 2020-11-15 19-52-29](https://user-images.githubusercontent.com/31929374/99187358-38f5e880-277c-11eb-8892-1254c2b6d24d.png)

**Comment by tamuratak** [comment]
See https://github.com/microsoft/vscode/issues/107997#issuecomment-703245178
