### ISSUE TITLE
Is there key bindings for mac os

### ISSUE THREAD

**Issue by lazarvgd** [bnxm/dart-data-class-generator#32]
Hello, I am looking for keyboard shortcuts for mac, I cannot use the library with the provided shortcuts.
Can you please advice? 

thanks 👍

**Comment by bnxm** [comment]
I don't use mac os so I don't know the exact key bindings, but the extensions utilizes the same key bindings you would normally use for quick fix dialog, etc. so you might have to take a look at your settings.

**Comment by francesctovar** [comment]
CMD + .
