### ISSUE TITLE
[feature request] disable overriding

### ISSUE THREAD

**Issue by Silfalion** [bnxm/dart-data-class-generator#38]
is it possible to disable the overriding for the generated functions? sorry if it exists and I'm duplicating, didn't find when searching.

Edit: there is a similar feature, but the aim would be to add the changes that don't override the old ones, adding stuff not overriding.

**Comment by bnxm** [comment]
You can only generate the functions you need to generate using the quick fixes. Preserving custom changes would require to calculate the diff which is too much work for me. Sorry.
