### ISSUE TITLE
I don't want to use null-safety yet. Why it started adding '@required' and '?'

### ISSUE THREAD

**Issue by yasinarik** [bnxm/dart-data-class-generator#45]
Hi, it may seem like a question but I think it is the right place to ask since this might be an issue also.

For the last month, I've been using this plugin. Today, I realized that it generates code suitable for null-safety.

It wasn't like that before. How to switch back? Or is it related to my Flutter setup? I didn't change anything.  Same Flutter version 1.25.0, same project. 

### Constructor
```dart
class RegionData {
  List<CountryData> countries;
.
.
.

= const [], // Before it was like that and I want it to stay the same.
required this.countries,  // Now, it produces code like this. 
```

### Copy With method
```dart
RegionsData copyWith({
.
.
.
   List<CountryData> countries?, // It adds to '?' mark. But before it didn't add that.
```

**Comment by bnxm** [comment]
Yes, I migrated the extension to null safety because it is now on stable and there is no reason not to use it aside from the effort it takes to migrate your app. 

If you want to use the older version without null safety, you would have to download the previous version from the market place and install it locally.

**Comment by yasinarik** [comment]
> there is no reason not to use it aside from the effort it takes to migrate your app. 

Firstly, thanks for all the caring. I thought that is the reason and opened the issue if others face it too.

I haven't installed an extension without using VSCode's installer. I will search it. 

Obviously, you are right but I think there might be people still not using the null-safety because it's relatively new. 

Would you mind adding it as a preferable option where people can change in the "VSCode preferences"? (Or it is a bad idea, you know, it's up to you)
